---
server:
  port: 8080

  httpProxy:
    enabled: true
    port: 8443

  frontend:
    enabled: true
    port: 80

db:
  host: localhost
  port: 15432
  username: trackmyfish
  password: supersecretpassword
  name: trackmyfish
