on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        # Can't test on <1.16 as we're using embed, which wasn't introduced
        # until 1.16
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
